### PR TITLE
Do not add empty endpoint.

### PR DESCRIPTION
**Pull request by davinchia**
Today we use almost all the available S3 configuration options to either log to Minio or S3. We switch on this by injecting run time env var as such,

Minio:
```
S3_LOG_BUCKET=airbyte-dev-logs
S3_LOG_BUCKET_REGION=
AWS_ACCESS_KEY_ID=minio
AWS_SECRET_ACCESS_KEY=minio123
S3_MINIO_ENDPOINT=http://airbyte-minio-svc:9000
S3_PATH_STYLE_ACCESS=true
```

S3:
```
S3_LOG_BUCKET=airbyte-dev-logs
S3_LOG_BUCKET_REGION=us-west-2
AWS_ACCESS_KEY_ID=key-id
AWS_SECRET_ACCESS_KEY=access-key
S3_MINIO_ENDPOINT=
S3_PATH_STYLE_ACCESS=
```

This is pulled in via Log4j2's env var syntax. `S3_MINIO_ENDPOINT=` is set to `s3ServiceEndpoint` in the appender.

Because we want to switch at run time, we have to assume the `S3_MINIO_ENDPOINT=` env var exists. Since it does not have any value, the variable resolves to an empty string. The appender does not recognise the empty string and tries to add it. This errors out since either region or endpoint can be set, but not both.

This PR checks for an empty string before setting the service endpoint.

### CODE REVIEW

**Comment by davinchia** [comment]
@bluedenim would appreciate if it you took a look!

**Comment by bluedenim** [comment]
This works, but there is a easier way with a helper [StringUtils.isTruthy()](https://github.com/bluedenim/log4j-s3-search/blob/master/appender-core/src/main/java/com/van/logging/utils/StringUtils.java#L15).

An example of how it's used: https://github.com/bluedenim/log4j-s3-search/blob/master/appender-core/src/main/java/com/van/logging/aws/S3Configuration.java#L189

There are other places that have yet to convert to this, though.

**Comment by davinchia** [comment]
@bluedenim I'll find some time to submit a cleaner pr. In the mean time, would appreciate if you release a new patch version so I can stop publishing my own fork :)

**Comment by bluedenim** [comment]
Release 3.1.1 is out

**Pull request merged**
